### ISSUE TITLE
[질문과 건의] 커밋 관련 내용입니다.

### ISSUE THREAD

**Issue by gusdn3477** [Heongilee/CodingTestStudy#24]
1) 일단 커밋 내역이 10개정도 쌓여서 풀리퀘스트를 해야 초기화 될 것 같아서 댓글 달아주시면 풀리퀘스트 올려놓겠습니다. (코드 수정은 없습니다.

2) 혹시 repository 설정 한번만 확인해 주실 수 있나요? github desktop 문제가 아닌 것 같아 질문 드립니다.

**Comment by Heongilee** [comment]
현재까지 repository 설정을 하나씩 보았는데, 건드릴만한 부분이나 구글링을 해도 정보가 딱히 없는 것 같습니다...

https://github.com/Heongilee/CodingTestStudy/discussions/32
이 링크에 제가 Github Desktop 사용하는 화면을 녹화해서 업로드 해봤는데 이 방법대로 한번 해보시기 바랍니다. 제 부계정으로 한번 PR 테스트를 해봤는데 잘 되더군요,,, 혹시 모르니 구글링으로 저한테 문제가 있는지도 한번 더 찾아보겠습니다. 🙇🏻‍♂️

**Comment by gusdn3477** [comment]
네 알겠습니다. 일단 커밋 날리기 위하여 pull request 진행해 보겠습니다.

**Comment by gusdn3477** [comment]
브랜치를 새로 파지 않은 상태에서 진행해서 생긴 문제였습니다.
해결 방법을 알게 되어 close 하겠습니다.
